
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := logs

LOCAL_SRC_FILES	+= log.c logm.c

LOCAL_CFLAGS += -fPIC

LOCAL_C_INCLUDES += $(LOCAL_PATH)
LOCAL_C_INCLUDES += $(PREBUILT_HEADERS)/$(PLATFORM)_kdriver/include

LOCAL_EXPORT_C_INCLUDES := $(call all-c-headers-under, .)
LOCAL_EXPORT_COMPONENT_NAME := hal-libs
LOCAL_LIBRARY_VERSION := 0.1.0
include $(BUILD_BASE_SHARED_LIBRARY)

