
/*
 * SIC LABORATORY, LG ELECTRONICS INC., SEOUL, KOREA
 * Copyright(c) 2013 by LG Electronics Inc.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */


#include <linux/init.h>
#include <linux/linkage.h>
	__REFDATA

//	.section 	.cm3

//	.globl 	cm3_bin_start
//	.globl 	cm3_bin_end

ENTRY(cm3_bin_start)
//cm3_bin_start:
//incbin 		"/dtv/spt/jun.kong/git/os/lg115x_linux/drivers/kdriver/core/pm/cm3_ipc.bin"
//cm3_bin_end:
ENDPROC(cm3_bin_start)



