#-----------------------------------------------------------------------------------------
# M14 arch default devices
#-----------------------------------------------------------------------------------------
INCLUDE_KDRV_SAMPLE	:= NO
INCLUDE_KDRV_AAD	:= YES
INCLUDE_KDRV_AUDIO	:= YES
INCLUDE_KDRV_AFE	:= YES
INCLUDE_KDRV_CI		:= YES
INCLUDE_KDRV_DE		:= YES
INCLUDE_KDRV_DEMOD	:= YES
INCLUDE_KDRV_DENC	:= YES
INCLUDE_KDRV_FBDEV	:= YES
INCLUDE_KDRV_GFX	:= YES
INCLUDE_KDRV_GPU	:= YES
INCLUDE_KDRV_GPIO	:= YES
INCLUDE_KDRV_HDMI	:= YES
INCLUDE_KDRV_I2C	:= YES
INCLUDE_KDRV_PE		:= YES
INCLUDE_KDRV_PVR	:= YES
INCLUDE_KDRV_SDEC	:= YES
INCLUDE_KDRV_VBI	:= YES
#INCLUDE_KDRV_MMCU	:= YES
INCLUDE_KDRV_VDEC	:= YES
INCLUDE_KDRV_VENC	:= YES
INCLUDE_KDRV_PNG	:= YES
INCLUDE_KDRV_SE		:= YES
INCLUDE_KDRV_SYS	:= YES
INCLUDE_KDRV_SCI	:= YES
INCLUDE_KDRV_CLK	:= YES
INCLUDE_KDRV_MONITOR:= YES
INCLUDE_KDRV_MJPEG	:= YES
INCLUDE_KDRV_APR	:= YES
INCLUDE_KDRV_MEMPROT:= NO

INCLUDE_KDRV_BE		:= YES
INCLUDE_KDRV_LGBUS	:= YES
INCLUDE_KDRV_OVI	:= YES
INCLUDE_KDRV_LOGM 	:= YES
